// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  apiTest: {
    apiCompanyUrl: 'apitest.navigil.io/company/',
    apiDeviceUrl: 'apitest.navigil.io/devices/',
    apiUrl: 'apitest.navigil.io/',
    apiUser: 'apitest.navigil.io/user/',
  },
  apiProd: {
    apiCompanyUrl: 'apiprod.navigil.io/company/',
    apiDeviceUrl: 'apiprod.navigil.io/devices/',
    apiUrl: 'apiprod.navigil.io/',
    apiUser: 'apiprod.navigil.io/user/',
  },
  apiDev: {
    apiUrl: 'apidev.navigil.io/',
    apiDeviceUrl: 'apidev.navigil.io/devices/',
    apiUser: 'apidev.navigil.io/user/',
    apiCompanyUrl: 'apidev.navigil.io/company/',
  },
  apiOMDev: {
    apiUrl: 'apiomdev.navigil.io/',
    apiDeviceUrl: 'apiomdev.navigil.io/devices/',
    apiUser: 'apiomdev.navigil.io/user/',
    apiCompanyUrl: 'apiomdev.navigil.io/company/',
  },
  apiNavigilTest: {
    apiUrl: 'apinavigiltest.navigil.io/',
    apiDeviceUrl: 'apinavigiltest.navigil.io/devices/',
    apiUser: 'apinavigiltest.navigil.io/user/',
    apiCompanyUrl: 'apinavigiltest.navigil.io/company/',
  },
  apiUSTest: {
    apiUrl: 'apiustest.navigil.io/',
    apiDeviceUrl: 'apiustest.navigil.io/devices/',
    apiUser: 'apiustest.navigil.io/user/',
    apiCompanyUrl: 'apiustest.navigil.io/company/',
    wsUrl: 'wss://ntve5hm8ic.execute-api.us-east-1.amazonaws.com/ustest',
  },
};

export default awsconfig;
